import type { Metadata } from "next";
import { Darumadrop_One, Funnel_Sans, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "./_components/footer/footer";
import { Header } from "./_components/header/header";

const funnel = Funnel_Sans({
    variable: "--font-funnel",
    subsets: ["latin"]
});

const brand = Darumadrop_One({
    weight: "400",
    subsets: ["latin"]
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${funnel.variable} ${geistMono.variable}`}>
                <Header />
                <main>
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
